/*
  pagemeta.mjs, share metadata for every page listed in site-meta.json.

  Writes one delimited block per page so it is idempotent: run it again and it
  replaces its own block rather than stacking a second copy. Any og: or
  twitter: tag outside the block is removed first, so an older hand-written set
  cannot fight the generated one.

    bun .github/scripts/pagemeta.mjs         write the blocks
    bun .github/scripts/pagemeta.mjs check   exit 1 if any page has drifted
*/
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const META = JSON.parse(readFileSync(join(ROOT, 'site-meta.json'), 'utf8'));
const CHECK = process.argv[2] === 'check';

/* The site mark, inline so it costs no request. Read from the homepage so the
   two can never drift. */
const ICON = readFileSync(join(ROOT, 'index.html'), 'utf8').split('<link rel="icon" href="')[1].split('"')[0];

const START = '<!-- meta:start (generated by .github/scripts/pagemeta.mjs from site-meta.json) -->';
const END   = '<!-- meta:end -->';
const esc = (s) => String(s).replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]));
const slug = (p) => (p === '/' ? 'home' : p.replace(/^\/|\/$/g, '').replace(/[^a-z0-9]+/gi, '-').toLowerCase());
const fileFor = (p) => p.endsWith('.html') ? p.replace(/^\//, '') : join(p.replace(/^\//, ''), 'index.html');

function block(path, m) {
  const url = META.site + path;
  const img = META.site + '/media/og/' + slug(path) + '.png';
  return `${START}
<meta name="description" content="${esc(m.desc)}" />
<meta name="author" content="${esc(META.author)}" />
<meta name="theme-color" content="#0a0f16" />
<link rel="icon" href="${ICON}" />
<link rel="canonical" href="${url}" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="${esc(META.author)}" />
<meta property="og:url" content="${url}" />
<meta property="og:title" content="${esc(m.title)}" />
<meta property="og:description" content="${esc(m.desc)}" />
<meta property="og:image" content="${img}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="${esc(m.title)}. ${esc(m.card)}." />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${esc(m.title)}" />
<meta name="twitter:description" content="${esc(m.desc)}" />
<meta name="twitter:image" content="${img}" />
${END}`;
}

let changed = 0, drifted = [];
for (const [path, m] of Object.entries(META.pages)) {
  const file = join(ROOT, fileFor(path));
  if (!existsSync(file)) { console.warn('skip, no file: ' + path); continue; }
  let s = readFileSync(file, 'utf8');
  const want = block(path, m);

  let next;
  if (s.includes(START) && s.includes(END)) {
    next = s.slice(0, s.indexOf(START)) + want + s.slice(s.indexOf(END) + END.length);
  } else {
    /* Clear anything that would compete, then insert after </title>. */
    let t = s.replace(/[ \t]*<meta[^>]*(?:property="og:|name="twitter:)[^>]*>\r?\n?/g, '')
             .replace(/[ \t]*<meta[^>]*name="description"[^>]*>\r?\n?/g, '')
             .replace(/[ \t]*<meta[^>]*name="theme-color"[^>]*>\r?\n?/g, '')
             .replace(/[ \t]*<link[^>]*rel="canonical"[^>]*>\r?\n?/g, '')
             .replace(/[ \t]*<link[^>]*rel="icon"[^>]*>\r?\n?/g, '');
    const at = t.search(/<\/title>/i);
    if (at < 0) { console.warn('skip, no <title>: ' + path); continue; }
    const cut = at + '</title>'.length;
    next = t.slice(0, cut) + '\n' + want + t.slice(cut);
  }
  if (next === s) continue;
  if (CHECK) { drifted.push(path); continue; }
  writeFileSync(file, next);
  console.log('meta written: ' + path);
  changed++;
}
/* ---- sitemap and robots ----
   Derived from the same manifest, so a page cannot be described for sharing and
   then left out of the sitemap. Redirects, generated short links and the
   placeholder pages are deliberately absent: they all carry noindex. */
const EXTRA = ['/hp/games/'];
const urls = [...Object.keys(META.pages), ...EXTRA].sort();
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by .github/scripts/pagemeta.mjs from site-meta.json. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${META.site}${u}</loc></url>`).join('\n')}
</urlset>
`;
const robots = `# Generated by .github/scripts/pagemeta.mjs
User-agent: *
Allow: /

# Redirect shims and generated short links. They carry noindex too; this just
# saves crawlers the round trip.
Disallow: /s/
Disallow: /c/
Disallow: /r/
Disallow: /portfolio/
Disallow: /arcade/

Sitemap: ${META.site}/sitemap.xml
`;
for (const [name, body] of [['sitemap.xml', sitemap], ['robots.txt', robots]]) {
  const f = join(ROOT, name);
  const cur = existsSync(f) ? readFileSync(f, 'utf8') : null;
  if (cur === body) continue;
  if (CHECK) drifted.push(name);
  else { writeFileSync(f, body); console.log('wrote ' + name); changed++; }
}

if (CHECK) {
  if (drifted.length) {
    console.error('::error::page metadata has drifted from site-meta.json:');
    drifted.forEach(p => console.error('  - ' + p));
    console.error('  fix with: node .github/scripts/pagemeta.mjs');
    process.exit(1);
  }
  console.log(`Page metadata matches site-meta.json. ${Object.keys(META.pages).length} page(s).`);
} else console.log(`\n${changed} page(s) updated.`);
