#!/usr/bin/env bun
/*
  shortlinks.mjs, the whole link shortener.

  There is no database and no service. `s/links.json` is the source of truth and
  this script writes one tiny redirect folder per entry. That is an honest
  "database", it is version controlled, it costs nothing to host, and the links
  keep working for as long as the repo does.

  Why folders rather than `/s/?SLUG` or `/s/#SLUG`: a QR code has a mode for
  plain uppercase alphanumerics that packs 5.5 bits per character against 8 for
  byte mode, and its character set is `0-9 A-Z space $%*+-./:`. Neither `?` nor
  `#` is in it. Routing on a query or a fragment would force every QR into byte
  mode and throw the saving away, which is exactly the mistake most generators
  make. A path keeps `VI-ELLIS.COM/S/CV` inside the smallest QR that exists.

  Slugs are uppercase, which is the QR-friendly form and the one that goes on a
  card. GitHub Pages paths are case sensitive even though domains are not, so
  every other spelling, plus outright typos, is routed by /404.html.

  Usage:
    bun .github/scripts/shortlinks.mjs list
    bun .github/scripts/shortlinks.mjs add CV /resume.html "Public one-page résumé"
    bun .github/scripts/shortlinks.mjs rm CV
    bun .github/scripts/shortlinks.mjs build     regenerate every folder
    bun .github/scripts/shortlinks.mjs check     exit 1 if the folders have drifted
*/
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const DIR = join(ROOT, 's');
const DATA = join(DIR, 'links.json');
const SLUG_RE = /^[A-Z0-9]{1,8}$/;
/* Names that would shadow a real page, plus the two files that live in /s/. */
const RESERVED = new Set(['INDEX', 'LINKS', 'ADMIN', 'NEW', 'API']);

const load = () => (existsSync(DATA) ? JSON.parse(readFileSync(DATA, 'utf8')) : { links: {} });
const save = (d) => writeFileSync(DATA, JSON.stringify(d, null, 2) + '\n');
const esc = (s) => String(s).replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]));

/* One redirect page. Same shape as the hand-written /c/ alias already in this
   repo: a real <a> that works with no JavaScript, a meta refresh for the same
   reason, and replace() rather than assign() so the hop does not sit in the
   back button between the visitor and wherever they came from. Query and
   fragment are carried across explicitly. */
function page(slug, link) {
  const t = link.url;
  const abs = /^https?:\/\//i.test(t);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(link.title || slug)}</title>
<meta name="robots" content="noindex">
<link rel="canonical" href="${esc(t)}">
<meta http-equiv="refresh" content="0; url=${esc(t)}">
<!-- Generated by .github/scripts/shortlinks.mjs from s/links.json. Do not edit
     by hand, "bun .github/scripts/shortlinks.mjs build" will overwrite it. -->
<style>
  html { color-scheme: dark light; }
  body { margin: 0; min-height: 100vh; display: grid; place-items: center;
         font: 16px/1.5 ui-sans-serif, system-ui, sans-serif; text-align: center; padding: 24px; }
</style>
</head>
<body>
<p><noscript>This short link needs JavaScript, or follow the link. </noscript><a id="go" href="${esc(t)}">${esc(link.title || 'Continuing')}…</a></p>
<script>
  // A short link may still carry a query or a fragment of its own, so pass both
  // on. A fragment never reaches a server, so it has to be copied deliberately.
  // Merge rather than concatenate: the destination may already have a query of
  // its own, and "/?for=swe" + "?x=1" is not a URL.
  var target = ${JSON.stringify(t)};
  ${abs ? '' : `var q = location.search.slice(1), h = location.hash;
  if (q) target += (target.indexOf('?') >= 0 ? '&' : '?') + q;
  if (h && target.indexOf('#') < 0) target += h;`}
  document.getElementById('go').href = target;
  location.replace(target);
</script>
</body>
</html>
`;
}

function indexPage(links) {
  const rows = Object.entries(links).sort(([a], [b]) => a.localeCompare(b)).map(([slug, l]) =>
    `    <tr><td><a href="/s/${esc(slug)}">/s/${esc(slug)}</a></td><td>${esc(l.title || '')}</td><td class="u">${esc(l.url)}</td></tr>`
  ).join('\n');
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Short links</title>
<meta name="robots" content="noindex">
<style>
  :root { color-scheme: dark light; --ink:#e6eaf0; --bg:#0e1116; --soft:#9aa5b4; --line:#2a313c; }
  @media (prefers-color-scheme: light) { :root { --ink:#15202b; --bg:#eef1f4; --soft:#55606d; --line:#d7dee6; } }
  body { margin:0; background:var(--bg); color:var(--ink); padding:32px 20px;
         font:15px/1.55 ui-sans-serif,system-ui,sans-serif; }
  main { max-width:760px; margin:0 auto; }
  h1 { font-size:22px; margin:0 0 4px; }
  p.sub { color:var(--soft); margin:0 0 20px; font-size:13.5px; }
  table { width:100%; border-collapse:collapse; }
  th, td { text-align:left; padding:8px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { font-size:11.5px; text-transform:uppercase; letter-spacing:.08em; color:var(--soft); font-weight:600; }
  td.u { color:var(--soft); font-size:13px; word-break:break-all; }
  a { color:inherit; }
  .wrap { overflow-x:auto; }
</style>
</head>
<body>
<main>
  <h1>Short links</h1>
  <p class="sub">Generated from <code>s&#47;links.json</code>. Every entry is a real folder, so
     <code>VI-ELLIS.COM/S/CV</code> fits the smallest QR code there is.</p>
  <div class="wrap"><table>
    <thead><tr><th>Link</th><th>What</th><th>Goes to</th></tr></thead>
    <tbody>
${rows}
    </tbody>
  </table></div>
</main>
</body>
</html>
`;
}

function build({ check = false } = {}) {
  const d = load();
  const want = new Map();
  /* Uppercase only. A lowercase twin would be the tidy thing to ship, since
     GitHub Pages paths are case sensitive, but this repo is worked on from a
     Windows-backed filesystem where `s/cv` and `s/CV` are the same directory,
     so the pair cannot coexist in the working tree. /404.html routes every
     other spelling instead, which also catches typos. */
  for (const [slug, link] of Object.entries(d.links)) want.set(slug, page(slug, link));
  const problems = [];
  mkdirSync(DIR, { recursive: true });

  // stale folders first, so a removed slug stops resolving
  for (const name of readdirSync(DIR)) {
    const p = join(DIR, name);
    if (!statSync(p).isDirectory()) continue;
    if (want.has(name)) continue;
    if (check) problems.push(`stale folder /s/${name}`);
    else { rmSync(p, { recursive: true, force: true }); console.log(`removed /s/${name}`); }
  }
  for (const [name, html] of want) {
    const f = join(DIR, name, 'index.html');
    const cur = existsSync(f) ? readFileSync(f, 'utf8') : null;
    if (cur === html) continue;
    if (check) problems.push(`/s/${name} is ${cur === null ? 'missing' : 'out of date'}`);
    else { mkdirSync(join(DIR, name), { recursive: true }); writeFileSync(f, html); console.log(`wrote /s/${name}`); }
  }
  const idx = indexPage(d.links);
  const idxFile = join(DIR, 'index.html');
  const curIdx = existsSync(idxFile) ? readFileSync(idxFile, 'utf8') : null;
  if (curIdx !== idx) {
    if (check) problems.push('/s/index.html is out of date');
    else { writeFileSync(idxFile, idx); console.log('wrote /s/index.html'); }
  }
  if (check && problems.length) {
    console.error('::error::short links have drifted from s/links.json:');
    problems.forEach(p => console.error('  - ' + p));
    console.error('  fix with: bun .github/scripts/shortlinks.mjs build');
    process.exit(1);
  }
  if (check) console.log(`Short links match s/links.json. ${Object.keys(d.links).length} link(s).`);
}

const [cmd, ...rest] = process.argv.slice(2);
const d = load();
if (cmd === 'list' || !cmd) {
  const e = Object.entries(d.links).sort(([a], [b]) => a.localeCompare(b));
  if (!e.length) console.log('No short links yet.');
  for (const [slug, l] of e) console.log(`/s/${slug}`.padEnd(12) + (l.url + '').padEnd(46) + (l.title || ''));
} else if (cmd === 'add') {
  const slug = String(rest[0] || '').toUpperCase();
  const url = rest[1];
  const title = rest.slice(2).join(' ');
  if (!SLUG_RE.test(slug)) { console.error(`✋ "${rest[0]}" is not a usable slug. Use 1 to 8 characters, A-Z and 0-9 only, so it stays inside QR alphanumeric mode.`); process.exit(1); }
  if (RESERVED.has(slug)) { console.error(`✋ "${slug}" is reserved.`); process.exit(1); }
  if (!url) { console.error('✋ Needs a destination.'); process.exit(1); }
  if (d.links[slug] && d.links[slug].url !== url) console.log(`(replacing /s/${slug}, was ${d.links[slug].url})`);
  d.links[slug] = { url, title: title || d.links[slug]?.title || '', added: d.links[slug]?.added || new Date().toISOString().slice(0, 10) };
  save(d); build();
  console.log(`\n/s/${slug} -> ${url}`);
} else if (cmd === 'rm') {
  const slug = String(rest[0] || '').toUpperCase();
  if (!d.links[slug]) { console.error(`✋ No /s/${slug}.`); process.exit(1); }
  delete d.links[slug]; save(d); build();
  console.log(`removed /s/${slug}`);
} else if (cmd === 'build') build();
else if (cmd === 'check') build({ check: true });
else { console.error('Commands: list, add, rm, build, check'); process.exit(1); }
